version: "3.7"

services: 
  api:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    
  ui:
    build: my-app
    ports:
      - 3000:3000
    # volumes:
    #   - ./frontend:/app